In [1]:
%matplotlib inline
import datacube
import numpy as np
dc = datacube.Datacube(app='dc-prueba1')
dc

Datacube<index=Index<db=PostgresDb<engine=Engine(postgresql://developer:***@localhost:5432/datacube)>>>

In [2]:
dc.list_products()

,name,description,platform,product_type,instrument,format,crs,resolution,tile_size,spatial_dimensions
id,,,,,,,,,,
18,ls5_ledaps_scene,Landsat 5 LEDAPS 25 metre,LANDSAT_5,ledaps,TM,GeoTiff,NaN,NaN,NaN,NaN
14,ls5_level1_scene,Landsat 5 Level 1 At-sensor Radiance 25 metre,LANDSAT_5,level1,TM,GeoTiff,NaN,NaN,NaN,NaN
15,ls5_nbar_scene,Landsat 5 NBAR 25 metre,LANDSAT_5,nbar,TM,GeoTiff,NaN,NaN,NaN,NaN
16,ls5_nbart_scene,Landsat 5 NBART 25 metre,LANDSAT_5,nbart,TM,GeoTiff,NaN,NaN,NaN,NaN
17,ls5_pq_scene,Landsat 5 PQ 25 metre,LANDSAT_5,pqa,TM,GeoTiff,NaN,NaN,NaN,NaN
13,ls5_satellite_telemetry_data,Landsat 5 Satellite Telemetry Data,LANDSAT_5,satellite_telemetry_data,TM,NaN,NaN,NaN,NaN,NaN
23,ls7_ledaps_albers,"Landsat 7 LEDAPS 25 metre, 100km tile, Austral...",LANDSAT_7,ledaps,ETM,NetCDF,EPSG:3577,"[-25, 25]","[100000.0, 100000.0]","(y, x)"
6,ls7_ledaps_scene,Landsat 7 LEDAPS 25 metre,LANDSAT_7,ledaps,ETM,GeoTiff,NaN,NaN,NaN,NaN
26,ls7_ledaps_utm,"Landsat 7 LEDAPS 25 metre, 100km tile, Austral...",LANDSAT_7,ledaps,ETM,NetCDF,EPSG:4326,"[-0.00027129759, 0.00027129759]","[1.0, 1.0]","(latitude, longitude)"
27,ls7_ledaps_utm18n,"Landsat 7 LEDAPS 30 metre, aprox 100km tile, (...",LANDSAT_7,ledaps,ETM,NetCDF,EPSG:32618,"[-30, 30]","[110580, 110580]","(y, x)"
28,ls7_ledaps_utm18n1,"Landsat 7 LEDAPS 30 metre, aprox 100km tile, (...",LANDSAT_7,ledaps,ETM,NetCDF,EPSG:32618,"[-30, 30]","[110580, 110580]","(y, x)"
29,ls7_ledaps_utm18n2,"Landsat 7 LEDAPS 30 metre, aprox 100km tile, (...",LANDSAT_7,ledaps,ETM,NetCDF,NaN,NaN,NaN,NaN
30,ls7_ledaps_utm18n3,"Landsat 7 LEDAPS 30 metre, aprox 100km tile, (...",LANDSAT_7,ledaps,ETM,NetCDF,EPSG:32618,"[-30, 30]","[110580, 110580]","(y, x)"
2,ls7_level1_scene,Landsat 7 Level 1 At-sensor Radiance 25 metre,LANDSAT_7,level1,ETM,GeoTiff,NaN,NaN,NaN,NaN
3,ls7_nbar_scene,Landsat 7 NBAR 25 metre,LANDSAT_7,nbar,ETM,GeoTiff,NaN,NaN,NaN,NaN
4,ls7_nbart_scene,Landsat 7 NBART 25 metre,LANDSAT_7,nbart,ETM,GeoTiff,NaN,NaN,NaN,NaN
5,ls7_pq_scene,Landsat 7 PQ 25 metre,LANDSAT_7,pqa,ETM,GeoTiff,NaN,NaN,NaN,NaN
1,ls7_satellite_telemetry_data,Landsat 7 Satellite Telemetry Data,LANDSAT_7,satellite_telemetry_data,ETM,NaN,NaN,NaN,NaN,NaN
12,ls8_ledaps_scene,Landsat 8 LEDAPS 25 metre,LANDSAT_8,LEDAPS,OLI_TIRS,GeoTiff,NaN,NaN,NaN,NaN
8,ls8_level1_scene,Landsat 8 Level 1 At-sensor Radiance 25 metre,LANDSAT_8,level1,OLI,GeoTiff,NaN,NaN,NaN,NaN
9,ls8_nbar_scene,Landsat 8 NBAR 25 metre,LANDSAT_8,nbar,OLI,GeoTiff,NaN,NaN,NaN,NaN
10,ls8_nbart_scene,Landsat 8 NBART 25 metre,LANDSAT_8,nbart,OLI,GeoTiff,NaN,NaN,NaN,NaN
11,ls8_pq_scene,Landsat 8 PQ 25 metre,LANDSAT_8,pqa,ETM,GeoTiff,NaN,NaN,NaN,NaN
7,ls8_satellite_telemetry_data,Landsat 8 Satellite Telemetry Data,LANDSAT_8,satellite_telemetry_data,OLI,NaN,NaN,NaN,NaN,NaN
19,modis_mcd43a1_tile,MODIS 500 metre MCD43A1,AQUA_TERRA,MCD43A1,MODIS,HDF4_EOS:EOS_GRID,NaN,NaN,NaN,NaN
20,modis_mcd43a2_tile,MODIS 500 metre MCD43A2,AQUA_TERRA,MCD43A2,MODIS,HDF4_EOS:EOS_GRID,NaN,NaN,NaN,NaN
21,modis_mcd43a3_tile,MODIS 500 metre MCD43A3,AQUA_TERRA,MCD43A3,MODIS,HDF4_EOS:EOS_GRID,NaN,NaN,NaN,NaN
22,modis_mcd43a4_tile,MODIS 500 metre MCD43A4,AQUA_TERRA,MCD43A4,MODIS,HDF4_EOS:EOS_GRID,NaN,NaN,NaN,NaN

In [5]:
nbar = dc.load(product='ls7_ledaps_utm', longitude=(-76, -73), latitude=(-1, 0), time=("2015-01-01","2016-12-01"))

In [8]:
nbar

<xarray.Dataset>
Dimensions:            (latitude: 3686, longitude: 3687, time: 1)
Coordinates:
  * time               (time) datetime64[ns] 2016-04-29T15:09:55
  * latitude           (latitude) float64 -0.0001356 -0.0004069 -0.0006782 ...
  * longitude          (longitude) float64 -74.0 -74.0 -74.0 -74.0 -74.0 ...
Data variables:
    blue               (time, latitude, longitude) int16 -9999 20000 20000 ...
    green              (time, latitude, longitude) int16 -9999 20000 20000 ...
    red                (time, latitude, longitude) int16 -9999 20000 20000 ...
    nir                (time, latitude, longitude) int16 -9999 7367 7404 ...
    swir1              (time, latitude, longitude) int16 -9999 4968 5057 ...
    swir2              (time, latitude, longitude) int16 -9999 3483 3530 ...
    cf_mask            (time, latitude, longitude) int16 255 4 4 255 255 255 ...
    cf_mask_conf       (time, latitude, longitude) int16 255 0 0 0 0 0 0 0 0 ...
    adjacent_cloud_qa  (time, latitude, longitude) int16 255 255 255 255 255 ...
    atmos_opacity      (time, latitude, longitude) int16 -9999 -9999 -9999 ...
    cloud_qa           (time, latitude, longitude) int16 0 255 255 255 255 ...
    cloud_shadow_qa    (time, latitude, longitude) int16 0 0 0 0 0 0 0 0 0 0 ...
    ddv_qa             (time, latitude, longitude) int16 0 0 0 0 0 0 0 0 0 0 ...
    fill_qa            (time, latitude, longitude) int16 0 0 0 0 0 0 0 255 ...
    land_water_qa      (time, latitude, longitude) int16 0 255 255 255 255 ...
    snow_qa            (time, latitude, longitude) int16 0 0 0 0 0 0 0 0 0 0 ...
Attributes:
    crs: EPSG:4326

In [ ]:
nbar.data_vars["red"][0]

In [ ]:
np.sum((nbar.data_vars["blue"][0].values)==0)

In [ ]:
np.sum(np.logical_and((nbar.data_vars["blue"][0].values!=0), (nbar.data_vars["blue"][0].values!=-9999)))

In [ ]:
np.sum((nbar.data_vars["blue"][0].values)==-9999)